#!/usr/bin/env node
/**
 * PreToolUse guard for Edit / Write / MultiEdit / NotebookEdit.
 *
 * Blocks (exit 2, reason on stderr so Claude can recover without guessing):
 * - docs/archive/** (ADR-0033: not authority; humans only)
 * - generated artifacts that must be regenerated by their command
 * - .env files (secrets); .env.example stays editable
 * - the read-only v1 repository (E:\showzy)
 *
 * Fails open on malformed input so a hook bug never wedges a session.
 */
import path from "node:path";

const GENERATED = [
  ["packages/db/src/schema/auth.ts", "pnpm --filter @showzy/api auth:generate"],
  ["packages/contract/openapi.json", "pnpm --filter @showzy/contract openapi:generate"],
  ["apps/web/src/routeTree.gen.ts", "the TanStack Router plugin (vite dev/build)"],
];

function readStdin() {
  return new Promise((resolve) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => {
      data += chunk;
    });
    process.stdin.on("end", () => resolve(data));
    process.stdin.on("error", () => resolve(""));
  });
}

function block(reason) {
  process.stderr.write(`Blocked by .claude/hooks/guard-paths.mjs: ${reason}\n`);
  process.exit(2);
}

const raw = await readStdin();
let input;
try {
  input = JSON.parse(raw);
} catch {
  process.exit(0);
}

const toolInput = input?.tool_input ?? {};
const filePath = toolInput.file_path ?? toolInput.notebook_path ?? toolInput.path;
if (typeof filePath !== "string" || filePath.length === 0) process.exit(0);

const normalized = filePath.replaceAll("\\", "/");
const lower = normalized.toLowerCase();

// v1 repository: E:\showzy (but not E:\showzy-v2 or its worktrees).
if (/^(\/)?(e:|\/e|\/mnt\/e)\/showzy(\/|$)/.test(lower)) {
  block("the v1 repository (E:\\showzy) is read-only reference. Never modify it.");
}

// Resolve repo-relative path. Worktrees live under <repo>/.claude/worktrees/<name>/,
// so strip everything up to the innermost worktree root when present.
const projectDir = (process.env.CLAUDE_PROJECT_DIR ?? input?.cwd ?? process.cwd()).replaceAll("\\", "/");
let rel = normalized;
const worktreeMatch = normalized.match(/\/\.claude\/worktrees\/[^/]+\/(.*)$/);
if (worktreeMatch) rel = worktreeMatch[1];
else if (path.isAbsolute(normalized) || /^[a-zA-Z]:\//.test(normalized)) {
  const relative = path.posix.relative(projectDir.toLowerCase(), lower);
  rel = relative.startsWith("..") ? normalized : normalized.slice(normalized.length - relative.length);
}
rel = rel.replace(/^\.\//, "");

if (/^docs\/archive(\/|$)/i.test(rel)) {
  block("docs/archive/ is historical and not authority (ADR-0033). Do not edit it; ask the human.");
}

for (const [file, command] of GENERATED) {
  if (rel.toLowerCase() === file.toLowerCase()) {
    block(`${file} is generated. Change its source and regenerate with ${command}.`);
  }
}

if (/^packages\/db\/migrations\//i.test(rel) && process.env.SHOWZY_ALLOW_MIGRATION_EDIT !== "1") {
  block(
    "packages/db/migrations/ is drizzle-kit output. Change packages/db/src/schema/<module>.ts and run pnpm --filter @showzy/db db:generate. Hand-written SQL is only for ADR/spec-approved foundation primitives — ask the human.",
  );
}

// Worktree executors (subagents) never edit core; /scaffold sessions opt in.
if (worktreeMatch && /^packages\/core\//i.test(rel) && process.env.SHOWZY_ALLOW_CORE_EDIT !== "1") {
  block("packages/core is frozen for module tasks. Stop and report what core is missing (constitution.md).");
}

const base = path.posix.basename(rel).toLowerCase();
if (base === ".env" || (base.startsWith(".env.") && base !== ".env.example")) {
  block(".env files hold secrets and are never edited by agents. Update .env.example and tell the human.");
}

process.exit(0);
