import type { SuiteCoverageManifest } from "@showzy/core";

export const filesSuiteCoverage = {
  isolation: [
    "files.requestUpload",
    "files.getUploadUrl",
    "files.finalizeUpload",
    "files.getDownloadUrl",
    "files.getDownloadUrls",
    "files.getAttachmentFacts",
    "files.issueDocumentDownloadUrl",
    "files.issueShareDownloadUrl",
    "files.recordGeneratedObject",
    "files.requestSigningUpload",
    "files.getSigningUploadUrl",
    "files.recordSigningObject",
    "files.readPendingSigningObject",
    "files.issueSigningDownloadUrl",
    "files.issueShareSigningDownloadUrl",
    "files.issueSystemSigningDownloadUrl",
    "files.sweepAbandonedUploads",
    "files.backfillCatalogRenditions",
  ],
  publicProjection: [],
  consumerIsolation: [],
  accountIsolation: [],
  shareIsolation: [],
  idempotency: [
    "files.requestUpload",
    "files.finalizeUpload",
    "files.recordGeneratedObject",
    "files.requestSigningUpload",
    "files.recordSigningObject",
    "files.sweepAbandonedUploads",
    "files.backfillCatalogRenditions",
  ],
  events: [],
  atomic: [],
  jobIsolation: ["files"],
} as const satisfies SuiteCoverageManifest;
