export const SHO_CUSTOMER_WRITE_PARSES: Readonly<Record<string, unknown>> =
  Object.freeze({
    "d88-creates": {
      text: "створи клієнтку оксану осадчу",
      action: "customers.createCustomer",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        new_name: {
          text: "оксану осадчу",
        },
      },
      needs: [],
      ready: true,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "create",
      creates: {
        type: "customer",
        name: "Оксана Осадча",
      },
    },
    "d93-staff": {
      text: "додай нову працівницю дарину мельник телефон 0671112233",
      action: "customers.createCustomer",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        new_name: {
          text: "дарину мельник",
        },
        phone: {
          text: "0671112233",
          value: "0671112233",
        },
      },
      needs: [
        {
          path: "action",
          reason: "unsupported",
          blocking: true,
          span: {
            text: "працівницю",
          },
        },
      ],
      ready: false,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "create",
    },
    "d94-create-kept": {
      text: "додай клієнта з номером 050 334 12 90",
      action: "customers.createCustomer",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        phone: {
          text: "050 334 12 90",
          value: "0503341290",
        },
      },
      needs: [
        {
          path: "new_name",
          reason: "missing",
          blocking: true,
        },
      ],
      ready: false,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "create",
    },
    "d94-named-kept": {
      text: "знайди клієнта тимур савчин з номером 050 334 12 90",
      action: "customers.createCustomer",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        new_name: {
          text: "тимур савчин",
        },
        phone: {
          text: "050 334 12 90",
          value: "0503341290",
        },
      },
      needs: [],
      ready: true,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "create",
    },
    "d95-named-update": {
      text: "додай клієнту гончар коментар бере тільки оптом",
      action: "customers.updateCustomer",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        customer: {
          text: "гончар",
          status: "resolved",
          id: "c-honchar",
          name: "Віталій Гончар",
          match: "form",
        },
        comment: {
          text: "бере тільки оптом",
        },
      },
      needs: [],
      ready: true,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "update",
    },
    "d95-named-update-ru": {
      text: "добавь клиентке савчук комментарий забирает сама после обеда",
      action: "customers.updateCustomer",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        customer: {
          text: "савчук",
          status: "resolved",
          id: "c-savchuk",
          name: "Олена Савчук",
          match: "form",
        },
        comment: {
          text: "забирает сама после обеда",
        },
      },
      needs: [],
      ready: true,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "update",
    },
    "d95-named-unknown": {
      text: "додай клієнту марченко коментар платить карткою",
      action: "customers.updateCustomer",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        customer: {
          text: "марченко",
          status: "unknown",
          suggest: {
            action: "customers.createCustomer",
            params: {
              new_name: {
                text: "марченко",
              },
              comment: {
                text: "платить карткою",
              },
            },
          },
        },
        comment: {
          text: "платить карткою",
        },
      },
      needs: [
        {
          path: "customer",
          reason: "unknown",
          blocking: true,
        },
      ],
      ready: false,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "update",
    },
    "d95-pointer-kept": {
      text: "додай цьому клієнту гончар коментар бере оптом",
      action: "customers.updateCustomer",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        comment: {
          text: "бере оптом",
        },
        customer: {
          text: "цьому клієнту",
          status: "context",
        },
      },
      needs: [],
      ready: true,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "update",
    },
    "d95-noun-with-comment": {
      text: "додай клієнту коментар платить готівкою",
      action: "customers.updateCustomer",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        comment: {
          text: "платить готівкою",
        },
        customer: {
          text: "клієнту",
          status: "context",
        },
      },
      needs: [],
      ready: true,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "update",
    },
    "d79-group-update": {
      text: "признач групі салони партнерський прайс",
      action: "customers.updateGroup",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        group: {
          text: "салони",
          status: "resolved",
          id: "g-salons",
          name: "Салони",
          match: "exact",
        },
        price_list: {
          text: "партнерський",
          status: "resolved",
          id: "pl-partner",
          name: "Партнерський",
          match: "exact",
        },
      },
      needs: [],
      ready: true,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "create",
    },
    "d89-rename-group": {
      text: "перейменуй її на квітникарі",
      action: "customers.updateGroup",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        rename_to: {
          text: "квітникарі",
        },
        group: {
          text: "її",
          status: "context",
          id: "new-florists",
          name: "Флористи",
          focus: 0,
        },
      },
      needs: [
        {
          path: "action",
          reason: "read_as_focus_type",
          blocking: false,
          span: {
            text: "її",
          },
        },
      ],
      ready: true,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "update",
    },
    "d88-there-group": {
      text: "закинь туди ігоря литвина",
      action: "customers.setGroup",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        customers: [
          {
            text: "ігоря литвина",
            status: "resolved",
            id: "c-lytvyn",
            name: "Ігор Литвин",
            match: "form",
          },
        ],
        group: {
          text: "туди",
          status: "context",
          id: "new-wedding",
          name: "Весільні",
          focus: 1,
        },
      },
      needs: [],
      ready: true,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "update",
    },
    "d89-screen-when-chat-silent": {
      text: "закинь сюди ігоря литвина",
      action: "customers.setGroup",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        customers: [
          {
            text: "ігоря литвина",
            status: "resolved",
            id: "c-lytvyn",
            name: "Ігор Литвин",
            match: "form",
          },
        ],
        group: {
          text: "сюди",
          status: "context",
          id: "g-regular",
          name: "Постійні",
          focus: 1,
        },
      },
      needs: [],
      ready: true,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "update",
    },
    "d90-closed-restore": {
      text: "поверни її з архіву",
      action: "customers.restoreCustomer",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        customer: {
          text: "її",
          status: "context",
          id: "c-savchuk",
          name: "Олена Савчук",
          focus: 0,
        },
      },
      needs: [],
      ready: true,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "restore",
    },
    "d89-no-archive-asks": {
      text: "заархівуй її теж",
      action: "customers.archiveCustomer",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {},
      needs: [
        {
          path: "action",
          reason: "reference",
          blocking: true,
          span: { text: "її" },
        },
      ],
      ready: false,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "remove",
    },
    "d90-type-verb-offer": {
      text: "видали її вже нарешті",
      action: "customers.deleteCustomer",
      kind: "high",
      effect: "destructive",
      confirm: "strong",
      params: {
        customer: {
          text: "її",
          status: "context",
          id: "new-zlata",
          name: "Злата Коваль",
          focus: 0,
        },
      },
      needs: [
        {
          path: "action",
          reason: "read_as_focus_type",
          blocking: false,
          span: { text: "її" },
        },
        {
          path: "customer",
          reason: "check_reference",
          blocking: true,
          span: { text: "її" },
        },
      ],
      ready: false,
      refPrevious: {},
      catalogued: false,
      domain: "orders",
      verb: "cancel",
    },
    "d93-customer-group-kept": {
      text: "заведи групу клієнтів гуртівня",
      action: "customers.createGroup",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        new_name: {
          text: "гуртівня",
        },
      },
      needs: [],
      ready: true,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "create",
    },
    "d93-product-group": {
      text: "заведи групу продукції випічка",
      action: "customers.createGroup",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        new_name: {
          text: "випічка",
        },
      },
      needs: [
        {
          path: "action",
          reason: "unsupported",
          blocking: true,
          span: { text: "групу продукції" },
        },
      ],
      ready: false,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "create",
    },
    "d78-unknown-group": {
      text: "переведи оксану мельник і шевчука в групу гуртові",
      action: "customers.setGroup",
      kind: "write",
      effect: "write",
      confirm: "card",
      params: {
        customers: [
          {
            text: "оксану мельник",
            status: "resolved",
            id: "c-oksana",
            name: "Оксана Мельник",
            match: "form",
          },
          {
            text: "шевчука",
            status: "unknown",
            nearest: [{ id: "c-shev", name: "Шевченко", score: 0.7 }],
            suggest: {
              action: "customers.createCustomer",
              params: { new_name: { text: "шевчука" } },
            },
          },
        ],
        group: {
          text: "гуртові",
          status: "unknown",
          suggest: {
            action: "customers.createGroup",
            params: { new_name: { text: "гуртові" } },
          },
        },
      },
      needs: [
        { path: "customers[1]", reason: "unknown", blocking: true },
        { path: "group", reason: "unknown", blocking: true },
      ],
      ready: false,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "update",
    },
    "d88-this-group-screen": {
      text: "видали цю групу",
      action: "customers.deleteGroup",
      kind: "high",
      effect: "destructive",
      confirm: "strong",
      params: {
        group: {
          text: "цю групу",
          status: "context",
          id: "new-wedding",
          name: "Весільні",
          focus: 0,
        },
      },
      needs: [],
      ready: true,
      refPrevious: {},
      catalogued: false,
      domain: "customers",
      verb: "remove",
    },
  });

export function shoCustomerWriteParse(caseId: string): unknown {
  const parse = SHO_CUSTOMER_WRITE_PARSES[caseId];
  if (parse === undefined) {
    throw new Error(`no conformance parse ${caseId}`);
  }
  return parse;
}
