import type { SuiteCoverageManifest } from "@showzy/core";

export const assistantSuiteCoverage = {
  isolation: [
    "assistant.createConversation",
    "assistant.listConversations",
    "assistant.getStaffActor",
    "assistant.readChatState",
    "assistant.writeChatState",
    "assistant.readChatMessages",
    "assistant.insertChatMessage",
    "assistant.updateChatMessage",
    "assistant.acceptTurn",
    "assistant.startTurn",
    "assistant.finishTurn",
    "assistant.listStaleTurns",
    "assistant.readTurnForJob",
    "assistant.interruptTurn",
    "assistant.listOverdueTurns",
    "assistant.sweepOverdueTurns",
    "assistant.readActiveTurn",
    "assistant.readLatestInterruptedTurn",
  ],
  publicProjection: [],
  consumerIsolation: [],
  accountIsolation: [],
  shareIsolation: [],
  idempotency: ["assistant.createConversation"],
  events: [],
  atomic: [],
  jobIsolation: [],
} as const satisfies SuiteCoverageManifest;
