/**
 * The event envelope as delivered to consumer actions (fnd-T17 —
 * core.md §6). The delivery entrypoint builds this shape from the stored
 * outbox row and passes it as the bound action's **input**, so the module's
 * own Zod schema (built with `eventEnvelopeSchema`) validates it like any
 * other action input.
 *
 * The envelope is JSON-safe by construction: consumer actions are audited
 * write actions, and the audit protocol hashes the validated input as RFC
 * 8785 canonical JSON (core.md §8) — a `Date` or `bigint` in the input
 * would break that. Hence `occurredAt` travels as an ISO-8601 string and
 * the per-aggregate `sequence` as a decimal string (int8 exceeds the JSON
 * number range; decimal strings are the platform's wire form for 64-bit
 * integers, db.md §3).
 */
import { z } from "zod";

import {
  actionChannelSchema,
  type ActionChannel,
} from "../../contract/channels.js";

/** The envelope's accountable emitter identity (core.md §6). */
export interface EventEnvelopeActor {
  /** Events accept user/system actors only — never anonymous (core.md §2). */
  readonly type: "user" | "system";
  readonly id: string;
  readonly channel: ActionChannel;
}

/** Aggregate reference with the monotonic per-aggregate sequence. */
export interface EventEnvelopeAggregate {
  readonly type: string;
  readonly id: string;
  /** Decimal string — int8 in the outbox, JSON-safe on the envelope. */
  readonly sequence: string;
}

/** One delivered domain event (core.md §6 envelope, JSON-safe form). */
export interface EventEnvelope<TPayload = unknown> {
  /** UUIDv7, generated by `ctx.emit`. */
  readonly eventId: string;
  readonly name: string;
  readonly version: number;
  /** ISO-8601 timestamp of the emission. */
  readonly occurredAt: string;
  /** Null for global-scope events (core.md §6). */
  readonly companyId: string | null;
  readonly aggregate: EventEnvelopeAggregate;
  readonly actor: EventEnvelopeActor;
  readonly requestId: string;
  readonly correlationId: string;
  /** The eventId or requestId that caused the emission. */
  readonly causationId: string;
  /** Validated against the event definition's schema at emit time. */
  readonly payload: TPayload;
}

/**
 * Builds the input schema of an event-bound consumer action: the envelope
 * with the consumed event's payload schema in the `payload` slot. Modules
 * use this so every consumer action validates the same envelope shape —
 * drift between what the dispatcher delivers and what a consumer expects
 * is then impossible by construction.
 */
export function eventEnvelopeSchema<TPayload extends z.ZodType>(
  payload: TPayload,
) {
  return z.object({
    eventId: z.uuid(),
    name: z.string().min(1),
    version: z.number().int().positive(),
    occurredAt: z.iso.datetime(),
    companyId: z.uuid().nullable(),
    aggregate: z.object({
      type: z.string().min(1),
      id: z.uuid(),
      sequence: z.string().regex(/^[0-9]+$/),
    }),
    actor: z.object({
      type: z.enum(["user", "system"]),
      id: z.string().min(1),
      channel: actionChannelSchema,
    }),
    requestId: z.string().min(1),
    correlationId: z.string().min(1),
    causationId: z.string().min(1),
    payload,
  });
}
