import {
  EXECUTOR_NONE,
  type ExecutorCase,
  type ExecutorItem,
} from "./corpus.js";

const item = (quantity: string, ...product: string[]): ExecutorItem => ({
  product,
  quantity,
});

export const HOLDOUT_CASES: readonly ExecutorCase[] = [
  {
    id: "h-colloquial-create-assign",
    uk: "Запиши Сергія Мельника в клієнти, номер 0661234567, і кинь його в оптовиків",
    jobs: ["create_customer", "assign_customer_to_group"],
    slots: {
      customerName: ["сергія мельника"],
      customerPhone: ["0661234567"],
      groupName: ["оптовиків"],
    },
    inflected: true,
  },
  {
    id: "h-order-no-verb",
    uk: "Два лате і один круасан для Олі",
    jobs: ["create_order"],
    slots: { customerName: ["олі"] },
    items: [item("2", "лате"), item("1", "круасан")],
    inflected: true,
  },
  {
    id: "h-negation",
    uk: "Не підтверджуй замовлення 1042, краще скасуй",
    jobs: ["cancel_order"],
    slots: { orderNumber: ["1042"] },
  },
  {
    id: "h-two-orders",
    uk: "Підтверди 1042 та 1043",
    jobs: ["confirm_order"],
    slots: { orderNumber: ["1042", "1043"] },
  },
  {
    id: "h-earned-month",
    uk: "Скільки ми заробили цього місяця?",
    jobs: ["count_orders"],
    slots: { period: ["this_month"] },
  },
  {
    id: "h-list-done-week",
    uk: "Покажи виконані замовлення за цей тиждень",
    jobs: ["list_orders"],
    slots: { period: ["this_week"], statusFilter: ["done"] },
  },
  {
    id: "h-find-question",
    uk: "Чи є у нас клієнт Бондаренко?",
    jobs: ["find_customer"],
    slots: { customerName: ["бондаренко"] },
  },
  {
    id: "h-raise-price",
    uk: "Підніми ціну на капучино до 70 гривень",
    jobs: ["change_product_price"],
    slots: { productName: ["капучино"], price: ["70"] },
  },
  {
    id: "h-new-product-colon",
    uk: "Новий товар: Матча лате, 95 грн",
    jobs: ["create_product"],
    slots: { productName: ["матча лате"], price: ["95"] },
  },
  {
    id: "h-invoice-bare-number",
    uk: "Виставити рахунок по 1060",
    jobs: ["issue_document"],
    slots: { orderNumber: ["1060"], documentType: ["payment_invoice"] },
  },
  {
    id: "h-implicit-cancel",
    uk: "Клієнт з замовлення 1055 передумав, знімай його",
    jobs: ["cancel_order"],
    slots: { orderNumber: ["1055"] },
  },
  { id: "h-unsupported-archive", uk: "Заархівуй товар Чізкейк", jobs: [] },
  { id: "h-unsupported-delete", uk: "Видали клієнта Тест Тестович", jobs: [] },
  {
    id: "h-unsupported-legal",
    uk: "Онови реквізити ФОП, у нас новий IBAN",
    jobs: [],
  },
  {
    id: "h-invite-personal",
    uk: "Створи запрошення для Ірини Мороз, одноразове",
    jobs: ["create_invite"],
    slots: { inviteKind: ["personal"] },
  },
  {
    id: "h-price-list-named",
    uk: "Зроби прайс для оптовиків і назви його Опт 2026",
    jobs: ["create_price_list"],
    slots: { priceListName: ["опт 2026"] },
  },
  {
    id: "h-chain-three-items",
    uk: "Додай клієнта Василь Ткач 0971112233, потім замовлення йому: 4 еспресо, 2 американо і тістечко, і одразу підтверди",
    jobs: ["create_customer", "create_order", "confirm_order"],
    slots: { customerName: ["василь ткач"], customerPhone: ["0971112233"] },
    items: [
      item("4", "еспресо"),
      item("2", "американо"),
      item(EXECUTOR_NONE, "тістечко"),
    ],
  },
  {
    id: "h-chain-group-list-assign",
    uk: "Створи групу Кав'ярні, прайс Кав'ярні опт, і додай у групу клієнта Кава Хаус",
    jobs: ["create_group", "create_price_list", "assign_customer_to_group"],
    slots: {
      groupName: ["кав'ярні"],
      priceListName: ["кав'ярні опт"],
      customerName: ["кава хаус"],
    },
  },
  {
    id: "h-chain-close-note-list",
    uk: "Закрий 1070, випиши накладну і покажи що ще лишилось нового",
    jobs: ["complete_order", "issue_document", "list_orders"],
    slots: {
      orderNumber: ["1070"],
      documentType: ["delivery_note"],
      statusFilter: ["new"],
    },
  },
  {
    id: "h-chain-cancel-recreate",
    uk: "Скасуй замовлення 1081 і створи нове для того ж клієнта Гриценка: 6 круасанів",
    jobs: ["cancel_order", "create_order"],
    slots: { orderNumber: ["1081"], customerName: ["гриценка"] },
    items: [item("6", "круасанів")],
    inflected: true,
  },
  {
    id: "h-chain-surzhyk",
    uk: "Заведи клієнта Саша Білий, закинь в віп групу і оформи заказ на 2 капучіно",
    jobs: ["create_customer", "assign_customer_to_group", "create_order"],
    slots: { customerName: ["саша білий"], groupName: ["віп"] },
    items: [item("2", "капучіно")],
  },
  {
    id: "h-confirm-by-customer",
    uk: "Підтверди замовлення Петренка",
    jobs: ["confirm_order"],
    slots: { customerName: ["петренка"] },
    inflected: true,
  },
  {
    id: "h-price-distractors",
    uk: "Замовлення для Олега: 3 лате по 65 і 2 круасани по 40",
    jobs: ["create_order"],
    slots: { customerName: ["олега"] },
    items: [item("3", "лате"), item("2", "круасани")],
    inflected: true,
  },
  {
    id: "h-quantity-not-a-candidate",
    uk: "Створи замовлення для Марини на півтора кіло кави",
    jobs: ["create_order"],
    slots: { customerName: ["марини"] },
    items: [item("1.5", "кави", "кіло кави")],
    inflected: true,
  },
  {
    id: "h-self-correction",
    uk: "Створи замовлення для Ігоря: 2 лате, ні, краще 3",
    jobs: ["create_order"],
    slots: { customerName: ["ігоря"] },
    items: [item("3", "лате")],
    inflected: true,
  },
  {
    id: "h-list-in-progress",
    uk: "Які замовлення зараз в роботі?",
    jobs: ["list_orders"],
    slots: { statusFilter: ["in_progress"] },
  },
  {
    id: "h-two-periods",
    uk: "Скільки нових замовлень сьогодні і скільки за тиждень?",
    jobs: ["count_orders"],
    slots: { period: ["today", "this_week"], statusFilter: ["new"] },
  },
  {
    id: "h-chat-with-business-words",
    uk: "Сьогодні багато замовлень, я втомився",
    jobs: [],
  },
  {
    id: "h-capability-not-request",
    uk: "Ти можеш виписувати рахунки?",
    jobs: [],
  },
  {
    id: "h-start-synonym",
    uk: "Розпочни замовлення 1090",
    jobs: ["start_order"],
    slots: { orderNumber: ["1090"] },
  },
  {
    id: "h-mixed-language",
    uk: "Create order для Anna: 2 flat white",
    jobs: ["create_order"],
    slots: { customerName: ["anna"] },
    items: [item("2", "flat white")],
  },
  {
    id: "h-assign-then-order",
    uk: "Додай Олену в групу Постійні та зроби їй замовлення на капучино",
    jobs: ["assign_customer_to_group", "create_order"],
    slots: { customerName: ["олену"], groupName: ["постійні"] },
    items: [item(EXECUTOR_NONE, "капучино")],
    inflected: true,
  },
];
