import type { SuiteCoverageManifest } from "@showzy/core";

export const catalogSuiteCoverage = {
  isolation: [
    "catalog.archiveProduct",
    "catalog.archiveVariant",
    "catalog.createProduct",
    "catalog.createVariant",
    "catalog.getProduct",
    "catalog.getProductOrderFacts",
    "catalog.getProductPricingFacts",
    "catalog.listProducts",
    "catalog.resolveLineReferences",
    "catalog.restoreProduct",
    "catalog.restoreVariant",
    "catalog.searchMatches",
    "catalog.setProductImages",
    "catalog.updateProduct",
    "catalog.updateVariant",
  ],
  publicProjection: [],
  consumerIsolation: [],
  accountIsolation: [],
  shareIsolation: [],
  idempotency: [
    "catalog.createProduct",
    "catalog.updateProduct",
    "catalog.createVariant",
    "catalog.updateVariant",
    "catalog.archiveProduct",
    "catalog.restoreProduct",
    "catalog.archiveVariant",
    "catalog.restoreVariant",
    "catalog.setProductImages",
  ],
  events: [],
  atomic: [],
} as const satisfies SuiteCoverageManifest;
