import { CoreInvariantError } from "@showzy/core/errors";
import { getConstructionPlans } from "pg-boss";
import pgBossPackage from "pg-boss/package.json" with { type: "json" };

export const PGBOSS_SCHEMA = "pgboss";
export const PGBOSS_MIGRATION_NAME = "pgboss";
export const pinnedPgBossVersion: string = pgBossPackage.version;
export const pinnedPgBossSchemaVersion: number = pgBossPackage.pgboss.schema;

const libraryTransactionOpen = "\n    BEGIN;\n";
const libraryTransactionClose = "\n    COMMIT;\n  ";

const librarySessionSettings = [
  /^SET LOCAL lock_timeout = \d+;$/,
  /^SET LOCAL idle_in_transaction_session_timeout = \d+;$/,
  /^SELECT pg_advisory_xact_lock\(.+\);$/,
];

const runtimeGrants = [
  `GRANT USAGE ON SCHEMA ${PGBOSS_SCHEMA} TO showzy_app;`,
  `GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${PGBOSS_SCHEMA} TO showzy_app;`,
  `REVOKE INSERT, DELETE ON ${PGBOSS_SCHEMA}.version FROM showzy_app;`,
  `ALTER DEFAULT PRIVILEGES IN SCHEMA ${PGBOSS_SCHEMA} GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO showzy_app;`,
];

function constructionStatements(): string {
  const plans = getConstructionPlans(PGBOSS_SCHEMA);
  if (
    !plans.startsWith(libraryTransactionOpen) ||
    !plans.endsWith(libraryTransactionClose)
  ) {
    throw new CoreInvariantError(
      `pg-boss ${pinnedPgBossVersion} construction plans are no longer framed by BEGIN/COMMIT`,
    );
  }
  const lines = plans
    .slice(libraryTransactionOpen.length, -libraryTransactionClose.length)
    .split("\n");
  librarySessionSettings.forEach((expected, index) => {
    if (!expected.test(lines[index]?.trim() ?? "")) {
      throw new CoreInvariantError(
        `pg-boss ${pinnedPgBossVersion} construction plans no longer open with the lock and timeout settings the generator strips`,
      );
    }
  });
  return lines.slice(librarySessionSettings.length).join("\n").trim();
}

export function pgBossMigrationSql(): string {
  return [
    `-- Generated by \`pnpm --filter @showzy/jobs pgboss:generate\` from pg-boss ${pinnedPgBossVersion}`,
    `-- getConstructionPlans("${PGBOSS_SCHEMA}"), schema version ${String(pinnedPgBossSchemaVersion)}. Do not edit.`,
    "-- Raw SQL approved by ADR-0041 J15 (docs/specs/jobs.md). The library's",
    "-- BEGIN/COMMIT and its SET LOCAL timeouts and advisory lock are dropped: the",
    "-- drizzle migrator already runs this file in its transaction.",
    constructionStatements(),
    "",
    "-- showzy_app grants for send, fetch and completion (ADR-0041, db.md §6).",
    ...runtimeGrants,
    "",
  ].join("\n");
}
